### ISSUE TITLE
Floatplane-Downloader will not start correctly. [VER 0.1.1]

### ISSUE THREAD

**Issue by RyoisMC** [alex73630/Floatplane-Downloader#7] opened 2017-11-10 17:52 UTC
https://pastebin.com/zUjr2FpK
Here is my output.
Command: "npm start" and "sudo npm start"
My config has correct login information. 
```
23 error Tell the author that this fails on your system:
23 error     node index.js
```
Node v6.11.4 NPM v3.5.2 FP-Downloader v0.1.1

**Comment by alex73630** [comment] 2017-11-10 18:34
Well... That's a strange error... 
I can't reproduce it with the same node and npm version in a Debian host.
Can you try to manually start the node script?
`node index.js`
You can also try to update npm:
`npm install -g npm@latest`

I prefer warning you, I haven't tested this script since the forum update so it could be totally broken.
And since the Floatplane website could launch soon, I can't promise any kind of support. (The disclaimer says it all)

I'll probably do some support/still working on it if the new website still offers to download content and if Plex support isn't planned.

**Comment by RyoisMC** [comment] 2017-11-10 20:33
``
module.js:471
    throw err;
    ^

Error: Cannot find module 'progress'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ryois/Floatplane-Downloader/index.js:3:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
ok updated NPM, retrying. I tried changing it from 91-the-floatpalne-club to 91-lmg-floatplane/ are there anymore refernces to the old url?

**Comment by alex73630** [comment] 2017-11-10 20:43
No but there is some lines of code that need to be modified in index.js (forum update changed some class names)
Here is the diff: https://github.com/alex73630/Floatplane-Downloader/pull/8/commits/22285980abddb22931ded6ccb3a8cf8674b40871

The error you send is more likely to be a missing dependency, try to re-run `npm install` to fix it.

**Comment by RyoisMC** [comment] 2017-11-10 20:46
yes, I wget'ed the new updated version. Yeah it persists after the new version.

**Comment by RyoisMC** [comment] 2017-11-10 20:46
added 93 packages in 21.364s
ooooh 🤞

**Comment by RyoisMC** [comment] 2017-11-10 20:48
https://i.imgur.com/H7KaqpG.gifv yay! Checking Plex server now!

**Comment by alex73630** [comment] 2017-11-10 20:51
Great! I'll merge the PR #8 and close this issue. If you have some Plex config issues, let me know here :)

**Comment by alex73630** [comment] 2017-11-10 21:21
Close #7

**Closed by alex73630** 2017-11-10 21:21 UTC
Labels: bug
